cc_library(
    name="nexus",
    deps=["//nexus/core:nexus-core"],
    visibility=["//visibility:public"],
)

test_suite(
    name = "unit-tests",
    tests = [
        "//nexus/core/test:unit-tests",
    ],
)
