cc_library(
    name="nexus-io",
    srcs=glob(["src/*.c"]),
    hdrs=glob(["include/virg/nexus/nx_*.h"]),
    includes=["include"],
    deps=["//nexus/core:nexus-core"],
    visibility=["//visibility:public"],
)
